<Project>

  <PropertyGroup>
    <VersionPrefix>0.1.0</VersionPrefix>
    <Authors>Sandefjord</Authors>
    <Company>Sandefjord</Company>
    <Product>GestPlan</Product>
    <Copyright>Copyright © 2026 Sandefjord — Tous droits réservés</Copyright>
    <NeutralLanguage>fr-FR</NeutralLanguage>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

</Project>
