// <auto-generated />
using System;
using GestPlan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestPlan.Data.Migrations
{
    [DbContext(typeof(GestPlanDbContext))]
    [Migration("20260917203758_ModeleMultiSite")]
    partial class ModeleMultiSite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("GestPlan.Core.Entites.Contrat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HeuresHebdomadaires")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PosteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quotite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TauxHoraireBrut")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("PosteId");

                    b.HasIndex("SiteId");

                    b.ToTable("Contrats");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstArchive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SitePrincipalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SitePrincipalId");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.EmployeSite", b =>
                {
                    b.Property<int>("EmployeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeId", "SiteId");

                    b.HasIndex("SiteId");

                    b.ToTable("EmployesSites");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.JournalAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CleEntite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomEntite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValeursApres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValeursAvant")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NomEntite", "CleEntite");

                    b.ToTable("JournauxAudit");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.Poste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CouleurAffichage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Postes");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.ReglesConformite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DureeMaximaleHebdomadaire")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DureeMaximaleQuotidienne")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DureePauseObligatoire")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DureeTravailContinuAvantPause")
                        .HasColumnType("TEXT");

                    b.Property<int>("JoursConsecutifsMaximum")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ReposHebdomadaireMinimum")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ReposQuotidienMinimum")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("ReglesConformite");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuseauHoraire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("HeureFermeture")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("HeureOuverture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashMotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SiteAssigneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NomUtilisateur")
                        .IsUnique();

                    b.HasIndex("SiteAssigneId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.Contrat", b =>
                {
                    b.HasOne("GestPlan.Core.Entites.Employe", "Employe")
                        .WithMany("Contrats")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestPlan.Core.Entites.Poste", "Poste")
                        .WithMany("Contrats")
                        .HasForeignKey("PosteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestPlan.Core.Entites.Site", "Site")
                        .WithMany("Contrats")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Poste");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.Employe", b =>
                {
                    b.HasOne("GestPlan.Core.Entites.Site", "SitePrincipal")
                        .WithMany("Employes")
                        .HasForeignKey("SitePrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SitePrincipal");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.EmployeSite", b =>
                {
                    b.HasOne("GestPlan.Core.Entites.Employe", "Employe")
                        .WithMany("SitesSecondaires")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestPlan.Core.Entites.Site", "Site")
                        .WithMany("SitesSecondaires")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.Poste", b =>
                {
                    b.HasOne("GestPlan.Core.Entites.Site", "Site")
                        .WithMany("Postes")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.ReglesConformite", b =>
                {
                    b.HasOne("GestPlan.Core.Entites.Site", "Site")
                        .WithOne("ReglesConformite")
                        .HasForeignKey("GestPlan.Core.Entites.ReglesConformite", "SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.Utilisateur", b =>
                {
                    b.HasOne("GestPlan.Core.Entites.Site", "SiteAssigne")
                        .WithMany()
                        .HasForeignKey("SiteAssigneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SiteAssigne");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.Employe", b =>
                {
                    b.Navigation("Contrats");

                    b.Navigation("SitesSecondaires");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.Poste", b =>
                {
                    b.Navigation("Contrats");
                });

            modelBuilder.Entity("GestPlan.Core.Entites.Site", b =>
                {
                    b.Navigation("Contrats");

                    b.Navigation("Employes");

                    b.Navigation("Postes");

                    b.Navigation("ReglesConformite");

                    b.Navigation("SitesSecondaires");
                });
#pragma warning restore 612, 618
        }
    }
}
